### ISSUE TITLE
JobResponseRecord multiplicity

### ISSUE THREAD

**Issue by gerardmoloneyetpartners** [ERDi-TestLab/ERDiTestlab-ProcessEvents#1]
The WorkExecutedEvent schema currently allows a single AddedJobResponseRecord.

It should allow for multiple AddedJobResponseRecords.

Proposed Fix is to insert the min/max occurs as per screenshot.
![image](https://user-images.githubusercontent.com/54049079/99341127-428a6800-28c4-11eb-9f6d-550471708b5f.png)

Other schemas may be affected and should be checked.

- WorkCommenced
- WorkExecuted
- WorkCompleted
- WorkRedirected
- WorkAborted

**Comment by gerardmoloneyetpartners** [comment]
- WorkCommenced is already set as [1..*] which is correct. at least 1 JobResponseRecord is required in this message type.
- WorkCompleted is already set as [1..*] which is correct. at least 1 JobResponseRecord is required in this message type.
- WorkRedirected is already set as [0..*] which is correct. JobResponseRecord is optional for this message type.
- WorkAborted is already set as [1..*] which is correct. at least 1 JobResponseRecord is required in this message type.

- WorkReconciled. Though not mentioned on original issue, WorkReconciled also has JobResponse and is looked at on the next comment.

**Comment by gerardmoloneyetpartners** [comment]
WorkReconciledEvent\JobResponseRecord

Looking further, things seem to be handled differently here.
Added/Changed/Deleted JobResponseRecord are all allowed, but as mandatory once only entry (that can be null) by the omission of a minOccurs/maxOccurs statement, thought there are 0..* JobResponses allowed per Record.

Current coding.
![image](https://user-images.githubusercontent.com/54049079/99764053-29d5b880-2b37-11eb-9a69-b9acf18e9756.png)

Proposed coding
![image](https://user-images.githubusercontent.com/54049079/99763960-f7c45680-2b36-11eb-9b19-de6c9e6926e8.png)


In light of looking also at the WorkReconciledEvent\JobResponseRecord\JobResponse multiplicity [0..*]
I would also propose the initial fix for WorkExecutedEvent\JobResponseRecord [0..*] also be updated to allow mutliple WorkExecutedEvent\JobResponseRecord\JobResponse [0..*]
as per below.

Current coding
![image](https://user-images.githubusercontent.com/54049079/99764265-a5376a00-2b37-11eb-80b2-283ba8b990e4.png)

Proposed Coding
![image](https://user-images.githubusercontent.com/54049079/99764369-e0399d80-2b37-11eb-814c-bbf0fd3a6a54.png)

**Comment by alexmarginet-mi** [comment]
No objections to the `WorkExecutedEvent` section of this issue.

Regarding the `WorkExecutedEvent` and `JobResponseRecord` part, does it make sense to have a both the `AddedJobResponseRecord` and the `JobResponse` objects as optional? That is, providing an `AddedJobResponseRecord` without a `JobResponse`?

The question is if, for example, this `WorkExcecuteEventType` would make sense?

```
<WorkExcecuteEventType>
   <AddedJobResponseRecord recordTypestamp="..." effectiveTimestamp="..." />
</WorkExcecuteEventType>
```
This is a valid xml that validates against the proposed xsd.

**Comment by gerardmoloneyetpartners** [comment]
@alexmarginet-mi 
Agreed, it would be better sense for 
JobResponseRecords to be 0 .. *
JobResponseRecords\JobResponse to be 1 .. *

I will update the proposed commit with this proposed coding for the WorkExecutedEventType
![image](https://user-images.githubusercontent.com/54049079/109464255-589dec00-7aa1-11eb-9dd0-cfa19981a44d.png)

**Comment by gerardmoloneyetpartners** [comment]
I propose the same adjustment to the WorkReconciledEventType where by,
JobResponseRecord become 0 .. *
JobResponseRecord\JobResponse becomes 1 .. *

![image](https://user-images.githubusercontent.com/54049079/109464725-145f1b80-7aa2-11eb-91dc-50d2dfc152e1.png)

**Comment by h28669** [comment]
We agree with changes to WorkReconciledEventType. Can you commit asap, so that in next sprint we can do the adaptions required by schema file changes. Thanks. Gianni

**Comment by gerardmoloneyetpartners** [comment]
Hi Gianni, I am working on it locally. The other pull reqeust is done, but I am testing this one locally, and it's not working on the workreconciled change.

**Comment by gerardmoloneyetpartners** [comment]
I have rolled back WorkReconciled changes.
this Issue and pull request now only deals with the WorkExecuted structure, and will be fixed as below.
![image](https://user-images.githubusercontent.com/54049079/111582096-4a680380-87f5-11eb-9ee8-9837a7fa6136.png)
