### ISSUE TITLE
Typo in OperationsScheduled and OperationsRescheduled

### ISSUE THREAD

**Issue by gerardmoloneyetpartners** [ERDi-TestLab/ERDiTestlab-ProcessEvents#16]
Several typos are found in the complextypes for OperationsScheduled and OperationsRescheduled

Line 226:       <xsd:element name="ChangedAddedMaterialLotRecord" minOccurs="0" maxOccurs="unbounded">
proposed fix should read 
Line 226:       <xsd:element name="ChangedMaterialLotRecord" minOccurs="0" maxOccurs="unbounded">

Line 324:      <xsd:element name="ChangedAddedMaterialLotRecord" minOccurs="0" maxOccurs="unbounded">
proposed fix should read
Line 324:      <xsd:element name="ChangedMaterialLotRecord" minOccurs="0" maxOccurs="unbounded">

Line 333      <xsd:element name="DeletedAddedMaterialLotRecord" minOccurs="0" maxOccurs="unbounded">
proposed fix should read
Line 333      <xsd:element name="DeletedMaterialLotRecord" minOccurs="0" maxOccurs="unbounded">

![image](https://user-images.githubusercontent.com/54049079/137257880-ed5d59bf-2254-4650-b3f5-074fabb82a08.png)

![image](https://user-images.githubusercontent.com/54049079/137257929-c6836040-e3b4-4faa-938f-0e73bd992a29.png)

**Comment by ETPartners** [comment]
closed with this merge
